### ISSUE TITLE
Adding Wordpress to the Docker image?

### ISSUE THREAD

**Issue by paulywill** [shahruk/Docker-Mac-Wordpress-Quickstart#1]
Bit of a confusion.

I was originally following the quickstart on Docker: https://docs.docker.com/compose/wordpress/

But after finding that getting to the data and migrating is a challenge I stumbled on your project.

Would there be any benefit to adding the setup of the Wordpress to the Docker compose file... or do you still believe the setup you have now of the Wordpress folder on your Mac and using the Git repo the way to go?

**Comment by shahruk** [comment]
Hi Pauly it's been a few years since I used this. I can't vouch for this method anymore, I've been using scotchbox and importing a sql file into the database manually.

Hope that helps

**Comment by paulywill** [comment]
@Diamons, yeah that does. Thanks! :)
